# Version: 0.1
FROM centos:centos6
MAINTAINER Anton Bugreev <anton@bugreev.ru>

## repo
RUN rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN rpm -Uvh http://li.nux.ro/download/nux/dextop/el6/x86_64/nux-dextop-release-0-2.el6.nux.noarch.rpm

## install vlc, tmpwatch
RUN yum install vlc-core tmpwatch -y

## add user for running vlc
RUN useradd vlc -u 1000

## setup dbus
RUN chown vlc:vlc /var/lib/dbus/ /var/run/dbus/ /var/run/ /var/lock/subsys/

## set timezone
RUN cp -f /usr/share/zoneinfo/Asia/Novosibirsk /etc/localtime

## Main
USER vlc
WORKDIR /home/vlc

